- apiVersion: config.openshift.io/v1
  kind: ImageDigestMirrorSet
  metadata:
    name: lvm-operator-imagedigestmirrors
  spec:
    imageDigestMirrors:
      - mirrors:
        - registry.stage.redhat.io/lvms4/lvms-operator-bundle
        - quay.io/redhat-user-workloads/logical-volume-manag-tenant/lvm-operator-bundle
        source: registry.redhat.io/lvms4/lvms-operator-bundle
      - mirrors:
        - registry.stage.redhat.io/lvms4/lvms-rhel9-operator
        - quay.io/redhat-user-workloads/logical-volume-manag-tenant/lvm-operator
        source: registry.redhat.io/lvms4/lvms-rhel9-operator
      - mirrors:
        - registry.stage.redhat.io/lvms4/lvms-must-gather-rhel9
        - quay.io/redhat-user-workloads/logical-volume-manag-tenant/lvms-must-gather
        source: registry.redhat.io/lvms4/lvms-must-gather-rhel9
      - mirrors:
        - quay.io/redhat-user-workloads/logical-volume-manag-tenant/lvm-operator-bundle
        source: registry.stage.redhat.io/lvms4/lvms-operator-bundle
      - mirrors:
        - quay.io/redhat-user-workloads/logical-volume-manag-tenant/lvm-operator
        source: registry.stage.redhat.io/lvms4/lvms-rhel9-operator
      - mirrors:
        - quay.io/redhat-user-workloads/logical-volume-manag-tenant/lvms-must-gather
        source: registry.stage.redhat.io/lvms4/lvms-must-gather-rhel9

- apiVersion: operators.coreos.com/v1alpha1
  kind: CatalogSource
  metadata:
    name: lvms-earlyaccess-catalog
    namespace: openshift-marketplace
  spec:
    displayName: "LVMS Early Access from Konflux"
    publisher: OpenShift QE
    sourceType: grpc
    updateStrategy:
      registryPoll:
        interval: 5m
    image: quay.io/redhat-user-workloads/logical-volume-manag-tenant/lvm-operator-catalog:v{{ ocp_version.split('.').0 }}.{{ ocp_version.split('.').1 }}
#    image: quay.io/redhat-user-workloads/logical-volume-manag-tenant/lvm-operator-catalog@sha256:c33b37ba2641239a4b63403a9e956962d1cd3fc80e25e4b71f448eb2db63684d
