---
# Infra part on ISAR:

disk_name: "lvms-disk1"
disk_size: "100Gi"
disk_storageclass:  "coe-netapp-san"
target_namespace: "{{ cluster_custom_namespace | default('stormshift-' + inventory_hostname + '-infra') }}"

# Actual LVMS Config:
lvms_namespace: "openshift-lvm-storage"
lvms_make_use_of_storage: true
lvms_default_storageclass: true
lvms_force_wipe: false
lvms_device_paths:
  - /dev/sda
