---
stormshift_owner_email: "dfroehli@redhat.com"
stormshift_owner_purpose: "Edge Testing"
stormshift_owner_usage: "exclusive"
cluster_type: classic
cluster_api_vip: 10.32.105.122
cluster_ingress_vip: 10.32.105.123

cluster_color: "#FF0"
# See: https://docs.openshift.com/container-platform/4.17/scalability_and_performance/enabling-workload-partitioning.html#enabling-workload-partitioning_enabling-workload-partitioning
#cluster_cpuPartitioningMode: AllNodes
cluster_cpuPartitioningMode: None
remove_cdrom_after_install: false

# See https://docs.openshift.com/container-platform/4.17/installing/overview/cluster-capabilities.html
cluster_capabilities:
#  baselineCapabilitySet: vCurrent
  baselineCapabilitySet: None
  additionalEnabledCapabilities:
  - baremetal
  - Ingress
  - Console
  - Storage
#  - OperatorLifecycleManager
#  - marketplace
#  - Insights

worker_storage_class: "odf-replica-two-block"
control_plan_storage_class: "odf-replica-two-block"
agent_iso_storage_class: "odf-replica-two-file"

# Default is in roles/cluster/defaults/main.yaml - Override if needed:
openshift_version: 4.18.29
#openshift_location: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp-dev-preview/{{ openshift_version }}"
#openshift_featureSet: TechPreviewNoUpgrade

control_plan_cores: 8
control_plan_ram_gb: 48

local_cluster_admins:
  - dfroehli@redhat.com-admin


control_plans:
  - vm_network_ip_address: 10.32.105.124
    vm_network_mac_address: 0E:C0:EF:20:69:7C
  - vm_network_ip_address: 10.32.105.125
    vm_network_mac_address: 0E:C0:EF:20:69:7D
  - vm_network_ip_address: 10.32.105.126
    vm_network_mac_address: 0E:C0:EF:20:69:7E

#arbiter_cores: 2
#arbiter_ram_gb: 8
#arbiters:
#  - vm_network_ip_address: 10.32.105.126
#    vm_network_mac_address: 0E:C0:EF:20:69:7E

worker_cores: 8
worker_ram_gb: 16

# Compact 3 nodes only Cluster:
workers: []
# Regular 3+3 Cluster:
# workers:
  # - vm_network_ip_address: 10.32.105.83
  #   vm_network_mac_address: 0E:C0:EF:20:69:53
  # - vm_network_ip_address: 10.32.105.84
  #   vm_network_mac_address: 0E:C0:EF:20:69:54
  # - vm_network_ip_address: 10.32.105.85
  #   vm_network_mac_address: 0E:C0:EF:20:69:55
# Use local quay as registry for faster installation:
cluster_additionalTrustBundle: /etc/pki/ca-trust/source/anchors/RedHat_Current-IT-Root-CAs.pem
cluster_imagesource:
 imageDigestSources:
 - source: quay.io/openshift-release-dev/ocp-release
   mirrorSourcePolicy: AllowContactingSource
   mirrorSourcePolicy: NeverContactSource
   mirrors:
     - quay.coe.muc.redhat.com/proxy_quay_openshift_release/ocp-release
 - source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
   mirrorSourcePolicy: NeverContactSource
   mirrors:
     - quay.coe.muc.redhat.com/proxy_quay_openshift_release/ocp-v4.0-art-dev
