kind: Namespace
apiVersion: v1
metadata:
  name: demo-appq
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: redhat-operators
#  namespace: openshift-operator-lifecycle-manager
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: registry.redhat.io/redhat/redhat-operator-index:v{{ ushift_version }}
  displayName: Red Hat Operators
  publisher: Red Hat
  grpcPodConfig:
    securityContextConfig: restricted
  updateStrategy:
    registryPoll:
      interval: 120m
---
kind: Subscription
apiVersion: operators.coreos.com/v1alpha1
metadata:
  name: datagrid-operator
  namespace: openshift-operators
spec:
  channel: 8.4.x
  installPlanApproval: Automatic
  name: datagrid
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: backend-datagrid
  namespace: demo-app
spec:
  service:
    type: DataGrid
    container:
      storage: 2Gi
  replicas: 2
  container:
    cpu: "2000m:10m"
    extraJvmOpts: '-XX:NativeMemoryTracking=summary'
    memory: "1G"
    storage: "1G"
  security:
    endpointEncryption:
      type: None
