# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
    - name: Set hostname
      tags: prep,hostname
      hostname:
        name: "{{inventory_hostname}}.{{ sysctx_dns_domain }}"

    - name: Disable SWAP since kubernetes can't work with swap enabled (1/2)
      tags: prep,swap
      changed_when: false
      shell: |
        swapoff -a

    - name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
      tags: prep,swap
      replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s.*)$'
        replace: '#\1'

#
# RHEL 92 todo:  work around
# Devices file sys_serial 213e7b6b-8441-44d0-ae26-3df55bab3844 PVID MDHwM81ex62inauoWm3U415rXNZCQigI last seen on /dev/sda2 not found.
# by:
#While awaiting a fix this can be bypassed by setting use_devicesfile=0 inside of /etc/lvm/lvm.conf

    - name: Workaround Devices files not found by changing LVM Configure
      tags: prep,lvmcfg
      replace:
        path: /etc/lvm/lvm.conf
        regexp: '# use_devicesfile = 1'
        replace: 'use_devicesfile = 0'

    - name: Register and Subscribe
      tags: prep,sub,slow
# redhat_subscription sometimes fails with "already registered, despite force"
# Hence we brute force it here:
      command: subscription-manager register --username {{ rhsm_user }} --password {{ rhsm_pswd }} --force --auto-attach --release 9.4

#     - name: Register and Subscribe
#       tags: prep,sub,slow
#       when: rhsm_user is defined
#       community.general.redhat_subscription:
#         state: present
#         username: "{{ rhsm_user }}"
#         password: "{{ rhsm_pswd }}"
#         auto_attach: true
#         force_register: true
# # TODO: Need to find a better way to determine OS version:
#         release: 9.4

    - name: Enable Repos
      tags: prep,repos, slow
      when: ushift_repo_list is defined
      rhsm_repository:
        state: enabled
        name: "{{ushift_repo_list}}"

    - name: Prepare for candidate Repos
#      when: dev_preview_version is defined
      tags: prep,repos
      template:
        trim_blocks: false
        src: templates/microshift-candidate.repo
        dest: /etc/yum.repos.d/microshift-candidate.repo

    - name: Install cockpit
      when: "'cockpit' in ushift_additional_features"
      tags: prep,cockpit
      yum:
        name:
          - cockpit
        state: present

    - name: Enable and start cockpit
      when: "'cockpit' in ushift_additional_features"
      tags: prep,cockpit
      service:
        name: cockpit.socket
        enabled: yes
        state: started
# Todo: add user for cockpit, root seems not to work easily

    - name: Add typical commands to bash history
      tags: prep, bash
      blockinfile:
        path: /root/.bash_history
        create: true
        marker: "# {mark} ANSIBLE MANAGED BLOCK {{inventory_hostname}}"
        block: "{{ lookup('template', 'templates/microshift-bash-history-suggestions.j2') }}"


    - name: Create crio dir
      tags: prep,crio
      file:
        path: /etc/crio
        state: directory

    - name: Provide pull secrets
      tags: prep,secrets
      copy:
        content: "{{image_pull_secret}}"
        dest: /etc/crio/openshift-pull-secret
        mode: 600
        owner: root
        group: root

    - name: Create kube dir
      tags: prep,cfg
      file:
        path: /root/.kube
        state: directory
        owner: root
        group: root

    - name: Create ushift dir
      tags: prep,cfg
      file:
        path: /etc/microshift
        state: directory
        owner: root
        group: root

    - name: Create LVM thin pool
      tags: prep,cfg
      lvol:
        vg: rhel
        lv: thin
        size: 16G
        opts: --thin

    - name: Provide MicroShift config file
      tags: prep,cfg
      template:
        src: templates/microshift-config.yaml.j2
        dest: /etc/microshift/config.yaml

    - name: Provide lvmd config file
      tags: prep,cfg
      template:
        src: templates/microshift-lvmd.yaml.j2
        dest: /etc/microshift/lvmd.yaml


    - name: Firewall add cluster network to trusted zone
      tags: prep, firewall
      firewalld:
        immediate: yes
        permanent: yes
        zone: trusted
        source: 10.42.0.0/16
        state: enabled

    - name: Firewall add DNS to trusted zone
      tags: prep, firewall
      firewalld:
        immediate: yes
        permanent: yes
        zone: trusted
        source: 169.254.169.1
        state: enabled

    - name: Firewall open API port for external access
      tags: prep, firewall
      firewalld:
        immediate: yes
        permanent: yes
        port: 6443/tcp
        state: enabled

    - name: Firewall open cockpit port for external access
      tags: prep, firewall
      firewalld:
        immediate: yes
        permanent: yes
        port: 9090/tcp
        state: enabled

    - name: Prep image registry proxy
      tags: prep, img_proxy
      when: ushift_use_local_quay_proxy
      ansible.builtin.file:
        path: /etc/containers/registries.conf.d/
        state: directory
        recurse: true
        mode: '0755'

    - name: Configure image registry proxy
      tags: prep, img_proxy
      when: ushift_use_local_quay_proxy
      template:
        trim_blocks: false
        src: templates/microshift-registries-proxy.conf
        dest: /etc/containers/registries.conf.d/100-microshift-proxy.conf

    - name: Add Red Hat Internal Root CA to trust local registry
      tags: prep, img_proxy
      when: ushift_use_local_quay_proxy
      copy:
        src: "/etc/pki/ca-trust/source/anchors/RedHat_Current-IT-Root-CAs.pem"
        dest: /etc/pki/ca-trust/source/anchors
        mode: 0644
        owner: root
        group: root
      register: ca_trust

    - name: Update CA Trust
      tags: prep, img_proxy
      when: ushift_use_local_quay_proxy and ca_trust is changed
      shell: update-ca-trust
