---

- name: Destroy VM
  ansible.builtin.include_tasks: 210-destroy-vm.yml
  tags: vm

- name: Remove DHCP and DNS
  ansible.builtin.include_role:
    name: "internal-configure-dhcp-dns"
    tasks_from: "destroy.yaml"
