---


- name: Slurp kubeadmin_password
  ansible.builtin.slurp:
    src: "{{ openshift_install_dir }}/auth/kubeadmin-password"
  register: slurp_kubeadmin_password

- name: Slurp kubeconfig
  ansible.builtin.slurp:
    src: "{{ openshift_install_dir }}/auth/kubeconfig"
  register: slurp_kubeconfig

- name: Store cluster credentials
  awx.awx.credential:
    name: "cluster_{{ cluster_name }}"
    organization: rbohne
    state: present
    credential_type: "OpenShift Cluster v1"
    inputs:
      api: https://api.{{ cluster_name }}.{{ base_domain }}:6443
      kubeadmin_password: "{{ slurp_kubeadmin_password['content'] | b64decode }}"
      kubeconfig: "{{ slurp_kubeconfig['content'] | b64decode }}"

- name: Add host
  awx.awx.host:
    name: "{{ cluster_name }}"
    description: "Single Node"
    inventory: sno
    state: present
    variables:
      ansible_host: "{{ network_ip_address }}"
      ansible_user: core

- name: Create group for cluster
  awx.awx.group:
    name: "cluster_{{ cluster_name }}"
    description: "Cluster {{ cluster_name }} Group"
    inventory: sno
    hosts:
      - "{{ cluster_name }}"