stormshift_owner_email: "dfroehli@redhat.com"
stormshift_owner_purpose: "Playground"
# Default is current GA version - see all.yaml
#ushift_version: "4.20"
ushift_actually_install: true
ushift_deploy_sample_workload: false
ushift_use_local_quay_proxy: false
vm_cores: 8
vm_memory: "24Gi"
network_ip_address: 10.32.99.9
network_mac_address: 0E:C0:EF:20:63:09

ushift_rhel_version: "9.4"
ushift_vm_template: "rhel94"
