stormshift_owner_email: "arolivei@redhat.com"
stormshift_owner_purpose: "TAM playground"
ushift_version: 4.18
ushift_preview_version: latest-4.19
ushift_preview_version_dep_ec: 4.19-el9-beta
ushift_preview_version_dep_rc: 4.19-el9-beta
# repo, one of: EC/RC/standard
ushift_repo: standard
ushift_actually_install: true
ushift_deploy_sample_workload: false
vm_cores: 4
vm_memory: "8Gi"
vm_template: "rhel94"
network_ip_address: 10.32.99.6
network_mac_address: 0E:C0:EF:20:63:06
ushift_repo_list:
      - rhocp-4.18-for-rhel-9-x86_64-rpms
      - fast-datapath-for-rhel-9-x86_64-rpms
      - gitops-1.12-for-rhel-9-x86_64-rpms
# install_type - one of: rpm, ostree, imageMode
ushift_install_type: rpm
