stormshift_owner_email: "bweidenb@redhat.com"
stormshift_owner_purpose: "ACM Demo Environment"
ushift_version: "4.16"
ushift_preview_version: latest-4.17
ushift_preview_version_dep_ec: 4.17-el9-beta
ushift_preview_version_dep_rc: 4.17-el9-beta
# repo, one of: EC/RC/standard
ushift_repo: standard
ushift_actually_install: true
ushift_deploy_sample_workload: true
vm_cores: 3
vm_memory: "16Gi"
ushift_vm_template: "rhel94"
network_ip_address: 10.32.99.20
network_mac_address: 0E:C0:EF:20:63:14
ushift_repo_list:
      - rhocp-4.16-for-rhel-9-x86_64-rpms
      - fast-datapath-for-rhel-9-x86_64-rpms
      - gitops-1.12-for-rhel-9-x86_64-rpms
# install_type - one of: rpm, ostree, imageMode
ushift_install_type: rpm
