stormshift_owner_email: "dfroehli@redhat.com"
stormshift_owner_purpose: "Playground"
ushift_version: "4.21"
ushift_preview_version: latest-4.22
ushift_preview_version_dep_ec: 4.22-el9-beta
ushift_preview_version_dep_rc: 4.22-el9-beta
# repo, one of: EC/RC/standard
ushift_repo: standard
ushift_actually_install: false
ushift_deploy_sample_workload: true
ushift_use_local_quay_proxy: true
vm_cores: 2
vm_memory: "4Gi"
network_ip_address: 10.32.99.7
network_mac_address: 0E:C0:EF:20:63:07

# install_type - one of: rpm, ostree, imageMode
ushift_install_type: rpm
