stormshift_owner_email: "dfroehli@redhat.com"
stormshift_owner_purpose: "Playground"
ushift_version: 4.19
ushift_preview_version: latest-4.18
ushift_preview_version_dep_ec: 4.19-el9-beta
ushift_preview_version_dep_rc: 4.19-el9-beta
# repo, one of: EC/RC/standard
ushift_repo: standard
ushift_actually_install: true
ushift_deploy_sample_workload: true
ushift_use_local_quay_proxy: false
vm_cores: 4
vm_memory: "8Gi"
ushift_vm_template: "rhel96"
ushift_rhel_version: "9.6"
network_ip_address: 10.32.96.111
network_mac_address: d4:f5:27:e7:23:3e
ushift_repo_list:
      - rhel-9-for-x86_64-appstream-eus-rpms
      - rhel-9-for-x86_64-baseos-eus-rpms
      - rhocp-4.19-for-rhel-9-x86_64-rpms
      - fast-datapath-for-rhel-9-x86_64-rpms
# install_type - one of: rpm, ostree, imageMode
ushift_install_type: rpm
