stormshift_owner_email: "dfroehli@redhat.com"
stormshift_owner_purpose: "Latest RC Build"
ushift_version: 4.19
ushift_preview_version: latest-4.20
ushift_preview_version_dep_ec: 4.20-el9-beta
ushift_preview_version_dep_rc: 4.20-el9-beta
# repo, one of: EC/RC/standard
ushift_repo: RC
ushift_actually_install: true
ushift_deploy_sample_workload: true
vm_cores: 2
vm_memory: "2Gi"
vm_template: "rhel96"
rhel_version: "9.6"
network_ip_address: 10.32.99.12
network_mac_address: 0E:C0:EF:20:63:0C
ushift_repo_list:
      - rhocp-4.20-for-rhel-9-x86_64-rpms
      - fast-datapath-for-rhel-9-x86_64-rpms
# install_type - one of: rpm, ostree, imageMode
ushift_install_type: rpm
