stormshift_owner_email: "dfroehli@redhat.com"
stormshift_owner_purpose: "Latest RC Build"
ushift_version: 4.16
ushift_preview_version: latest-4.16
ushift_preview_version_dep_ec: 4.15-el9-beta
ushift_preview_version_dep_rc: 4.15-el9-beta
# repo, one of: EC/RC/standard
ushift_repo: RC
ushift_actually_install: true
ushift_deploy_sample_workload: true
vm_cores: "2"
vm_memory: "2Gi"
vm_template: "rhel94"
network_ip_address: 10.32.99.12
network_mac_address: 0E:C0:EF:20:63:0C
ushift_repo_list:
      - rhocp-4.15-for-rhel-9-x86_64-rpms
      - fast-datapath-for-rhel-9-x86_64-rpms
      - gitops-1.12-for-rhel-9-x86_64-rpms
